# SAT Competition 2025 Configuration

solver_cputime: 5000
solver_walltime: 7000
solver_memory: 32768
checker_cputime: 45000
checker_walltime: 70000
checker_memory: 32768

scheduling:
  scheduler: slurm
  machine: cpuonly                  # slurm partition name
  account: hk-project-test-p0026435 # slurm account name
  reservation: sat2                 # slurm reservation name
  tasks_per_node: 7                 # slurm tasks per node
  jobname: satcomp25                # slurm job name
  workerinit: "export PYTHONNOUSERSITE=1; unset PYTHONPATH; source /home/hk-project-toolbox/fv2117/git/sc2026/dike-configs/venv/bin/activate; cd /home/hk-project-toolbox/fv2117/git/sc2026/dike"  # slurm initialization commands for each worker node, make sure to access the correct path to the virtual environment and the SustainableCompetition repository

benchmarks:
  file: ./instances.satcomp25.csv
  selection_method: allpairs

solvers: ./solvers.satcomp25.csv
results: ./satcomp25.results