# SAT Competition 2025 Configuration, but with reduced resource limits

# Solver resource limits
solver_cputime: 500          # CPU time limit for solvers in seconds
solver_walltime: 700         # Wall time limit for solvers in seconds
solver_memory: 65536         # Memory limit for solvers in MB

# Checker resource limits
checker_cputime: 4500        # CPU time limit for checkers in seconds
checker_walltime: 7000       # Wall time limit for checkers in seconds
checker_memory: 65536        # Memory limit for checkers in MB

# Job scheduler configuration
scheduling:
  scheduler: local
  parallel: 3                # Number of jobs run in parallel
  jobname: satcomp25local    # Job name for scheduler

benchmarks:
  file: ./satcomp25.instances.csv # Path to CSV containing benchmark hashes
  selection_method: random        # Methods: allpairs, random, discrimination-based, or variance-based
  stopping_criterion: percentage  # Stopping critieria: accuracy, percentage, wilcoxon
  stopping_threshold: 0.01        # Threshold for stopping criterion (e.g., accuracy percentage or p-value for Wilcoxon)

# Benchmark and solver files
solvers: ./satcomp25.solvers.csv      # Path to CSV containing solver paths
results: ./satcomp25local.results     # Path to directory for storing results